apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders3-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orderserver
        image: dimusha99/orders3-service
        ports:
        - containerPort: 4001