apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders3-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: ordernsserver
        image: 074338348268.dkr.ecr.ap-south-1.amazonaws.com/ordersn
        ports:
        - containerPort: 4001